---
application:
  name: "bluebotnow"
  project: "blue-bot-now"
  organization: "QoveryCommunity"
routers:
- name: "main-bluebotnow"
  routes:
  - application_name: "bluebotnow"
    paths:
    - "/*"
